name: Lint and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: true
        prerelease: true

    - name: Ensure lock file is up to date
      run: |
          pdm lock --check

    - name: Install dependencies
      run: |
        pdm sync -dG dev

    - name: Run Lint
      run: |
        pdm run lint
  
    - name: Run Tests
      run: |
        # not clear what's the right approach here https://github.com/pytest-dev/pytest/issues/5502
        # but we have some tests that show the behavior in this issue
        pdm run test --show-capture=log
