name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  release-to-pypi:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: "3.10"
    - name: Publish wheels
      run: |
        pdm publish
        # try to give Pypi time to update its index. Unfortunate.
        sleep 30s
      env:
        PDM_PUBLISH_USERNAME: __token__
        PDM_PUBLISH_PASSWORD: ${{ secrets.PYPI_PWD }}
